#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NETWORK="${NETWORK:-testnet}"
DEPLOYMENTS="$ROOT/deployments/${NETWORK}.json"
ENV_FILE="$ROOT/apps/web/.env.local"

if [[ ! -f "$DEPLOYMENTS" ]]; then
  echo "Missing $DEPLOYMENTS — run deploy-testnet.sh first" >&2
  exit 1
fi

VERIFIER=$(jq -r .verifier_contract_id "$DEPLOYMENTS")
ESCROW=$(jq -r .escrow_contract_id "$DEPLOYMENTS")
TOKEN=$(jq -r '.token_contract_id // "CDLZFC3SYJYDZT7K7VZ75HMSCV4MAZJSDLX4S5HD3NF4AXR7HWPN3NWA"' "$DEPLOYMENTS")
IMAGE=$(jq -r '.guest_image_id // empty' "$DEPLOYMENTS")

cat >"$ENV_FILE" <<EOF
# Generated by scripts/sync-env-from-deployments.sh — do not commit secrets
NEXT_PUBLIC_STELLAR_NETWORK=testnet
NEXT_PUBLIC_VERIFIER_CONTRACT_ID=$VERIFIER
NEXT_PUBLIC_ESCROW_CONTRACT_ID=$ESCROW
NEXT_PUBLIC_TOKEN_CONTRACT_ID=$TOKEN
EOF

if [[ -n "$IMAGE" && "$IMAGE" != "null" ]]; then
  echo "GUEST_IMAGE_ID=$IMAGE" >>"$ENV_FILE"
fi

echo "Wrote $ENV_FILE"
